### ISSUE TITLE
Better way to compress

### ISSUE THREAD

**Issue by sirenkovladd** [putoutjs/minify#10]
```js
import {minify} from '@putout/minify';
const js = `console.log(x + "g");`
const min = minify(js)
console.log(min)
```

```sh
❯ node tt.js
console.log(`${x}g`);
```

it seems that if you leave this line as an addition, the result will be smaller
```
console.log(`${x}g`);
console.log(x+'g');
```

is it not considered an option to either remove the conversion to template literals, or add a check of the original size?

**Comment by sirenkovladd** [comment]
But for 
```js
const js = `throw new Error('The language "' + r.language + '" has no grammar.');`
```

it was done differently
I think this is a mistake
because actually it would be better to use template literals here

**Comment by coderaiser** [comment]
We can add option to disable such transformation, about second case - it’s hard to implement, but PR’s a welcome

**Comment by coderaiser** [comment]
[Just landed](https://github.com/putoutjs/minify/releases/tag/v3.6.0) ability to disable `apply-template-literals` plugin 🎉 . Is it works for you?

**Comment by sirenkovladd** [comment]
As I understood in these changes, only that you turn off this transformation, without additional checking which of the options will be better

but unfortunately, the problem indicated in the title is not solved

**Comment by coderaiser** [comment]
There is no place I can add the check right now, but you can add a new rule to `minify` plugin which will check the size and apply transformation (instead of this one).

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝

**Comment by coderaiser** [comment]
Also this can be implemented using `@putout/minify` API, you can always run with one set of options, and then use another one and check which is better for you.
