### ISSUE TITLE
Continued template strings are not joined

### ISSUE THREAD

**Issue by adoxa** [putoutjs/minify#13]
- **Minify Version**: v11.2.0
- **Node Version**: v20.13.1
- **OS**: Windows 10 64-bit

Not sure if this technically counts as a bug or not, but since I'm using minify to create single-line bookmarklets it's definitely not what I want. This sequence:

```javascript
console.log(`1\
            2\
            3`);
```

is not minified, i.e. the backslashes and lines remain. The terser type does combine into a single line:

```javascript
console.log("1            2            3");
```

**Comment by coderaiser** [comment]
You want to convert this template literal to string literal?

**Comment by adoxa** [comment]
No (although I didn't actually see that), I want the line continuation to be removed so it's a single line, not remaining on multiple lines.

**Comment by coderaiser** [comment]
It's good idea, if you know how to do this, I'll merge this. Here is link to 🐊[**Putout Editor**](https://putout.cloudcmd.io/#/gist/61a299843b443fd84f0c3205da3506e7/2e55881a12efc6a270d46f87e727dc808ecddf84) to play with.

**Comment by adoxa** [comment]
[Updated](https://putout.cloudcmd.io/#/gist/61a299843b443fd84f0c3205da3506e7/9d7fb63f0e49732c1cef71887970157e70718d0e), including actual templates and a string literal.

**Comment by coderaiser** [comment]
Landed in [@putout/minify@3.14.0](https://github.com/putoutjs/minify/releases/tag/v3.14.0) 🎉.

Is it works for you?

**Comment by adoxa** [comment]
Not quite. My actual template ends with `\n`, which was added literally, so still a two-line script that won't work as a bookmarklet.
You didn't include the StringLiteral support?

**Comment by coderaiser** [comment]
Could you please provide examples? Here is implementation and tests: https://github.com/coderaiser/putout/tree/master/packages/plugin-minify/lib/join-continued-strings, you can send PR, or copy implementation to 🐊**Putout Editor** and provide new examples, for that you mentioned everything works good: https://github.com/putoutjs/minify/commit/1ef8f21ce59120fd85d12778ac76a5eede2ad5f4

**Comment by adoxa** [comment]
I'm on Windows, so my test file had CRLF, where the template worked, but the string didn't. After converting to LF:

```
>minify --version
v11.2.0

C:\Language\node-v20.13.1-win-x64\node_modules\minify\node_modules\@putout\minify>fgrep version package.json
  "version": "3.15.0",

>type test.js
console.log(`1\
            2\
            3\n`, '1\
            2\
            3\n');

>minify test.js
console.log(`1            2            3
`,'            2            3');
```
The template has a literal newline (for my use case it is undesired). The string has chopped off the first and last characters (that's why I used `cooked` in the editor, but using that in the bundle doesn't work).

**Comment by coderaiser** [comment]
The thing is `StringLiteral` has no `cooked` property:

<img width="278" alt="image" src="https://github.com/putoutjs/minify/assets/1573141/5fe1cc43-1629-4681-a094-ea10b8f70bb8">

Anyways, if you have ideas how to make it work, you can send PR, and I'll merge it.

**Comment by adoxa** [comment]
It worked in the editor, though. Hm, just tried changing `value` to `cooked` in the bundle (`minify.min.js`) again and now it does work.

```
>minify test.js
console.log(`1            2            3
`,'1            2            3
');
```

Still got that literal newline, which is an actual bug for a string. Ah, [here we go](https://putout.cloudcmd.io/#/gist/61a299843b443fd84f0c3205da3506e7/ae07aa2440b6952947071f0b56a5462596b180d8), looks like StringLiteral expects the quotes, that explains the chopped off characters. Using `cooked.replaceAll` didn't work, so `value` it is.

**Comment by coderaiser** [comment]
Just updated! Is it works for you?

**Comment by adoxa** [comment]
Yep!
