### ISSUE TITLE
Incorrect order of initialization variables

### ISSUE THREAD

**Issue by sirenkovladd** [putoutjs/minify#18]
- **Version** (`npm -v`): 10.5.2
- **Node Version** `node -v`: v20.13.1
- **OS** (`uname -a` on Linux): Darwin arm64

Incorrect order of initialization variables

```js
import { minify } from "@putout/minify";

const source = `
const c = (e) => e.w;
const w = (c) => c;
function f(e) {
  const { n } = e;
  e.w = n;
  const q = c(e);
  return q && w(q)
}
console.log(f({n:1}))`;

eval(source);
const result = minify(source);
console.log(result);
eval(result);
```

```sh
❯ node test.js
1
var c=e=>e.w,w=c=>c;function f(e){var{n}=e,q=c(e);e.w=n;return q&&w(q)}console.log(f({n:1}));
undefined
```

**Comment by coderaiser** [comment]
Fixed in #17 🎉. Is it works for you?

**Comment by sirenkovladd** [comment]
No, same result
```json
"dependencies": {
    "@putout/minify": "^3.16.0"
  }
```

**Comment by coderaiser** [comment]
Try to re-install `@putout/minify`.

**Comment by sirenkovladd** [comment]
```sh
❯ node index.js
1
var c=e=>e.w,w=c=>c;function f(e){const{n}=e,q=c(e);e.w=n;return q&&w(q)}console.log(f({n:1}));
undefined

❯ cat node_modules/@putout/minify/package.json | jq '.version'
"3.17.1"
```

**Comment by coderaiser** [comment]
Added ability to disable `mergeVariables`.

**Comment by sirenkovladd** [comment]
But it's a useful feature I'd like to use
the problem is that it may not work correctly in such scenarios

**Comment by coderaiser** [comment]
Here is [the code](https://github.com/coderaiser/putout/blob/master/packages/plugin-minify/lib/merge-variables/index.js), you can play with it, if you get any ideas how to make this work, I’ll merge.

**Comment by coderaiser** [comment]
Fixed in latest version of `@putout/minify` 🎉
