### ISSUE TITLE
More examples of the effectiveness of this minifier

### ISSUE THREAD

**Issue by sirenkovladd** [putoutjs/minify#25]
### Describe more [How it's compared to Terser?](https://github.com/putoutjs/minify?tab=readme-ov-file#how-its-compared-to-terser)

*I would like to make a discussion, but there is no way to do so in this repository*

could you make a separate folder in which there will be a script comparing the effectiveness of this minifier with others (Terser, rspack, esbuild, Bun)
it is desirable that it be several popular libraries (for example, React, Vue, Lodash, three.js)

and show the result in terms of compression level and execution speed

**Comment by coderaiser** [comment]
Do you willing to help with this? I have no time for this.

**Comment by sirenkovladd** [comment]
I think I can do it

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝
Reopen when you need
