### ISSUE TITLE
Increments are minified incorrectly

### ISSUE THREAD

**Issue by atjn** [putoutjs/minify#8]
- **Version** (`npm -v`): 10.2.5
- **Node Version** `node -v`: 20.10.0

Hello and thank you for making this tool :)

It seems there is a major bug in how increments and decrements are treated. The parser will happily produce output that
a) cannot be parsed, and
b) is not equivalent to the original code.

Example 1:
`a++; a++;` minify -> `a++++;` (syntax error)

Example 2:
`if(_){a++}else{a--}` minify -> `if(_){}else a++--` (syntax error + not the same code, increment is moved from `if(true)` to `if(false)`)

I don't have time to understand the bug further, or test if it is applicable to more unary operators, sorry.

**Comment by coderaiser** [comment]
Thanks! [Just fixed](https://github.com/putoutjs/minify/releases/tag/v3.1.0) 🎉 . Is it works for you?

**Comment by atjn** [comment]
Thank you for the very quick fix! It works now :)
